version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp

  laravelapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './laravel:/app'
    depends_on:
      - mariadb

  api:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - "8001:8000"
